version: '3.9'
services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${SECURITY_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - /data/database:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    command: -driver=${SECURITY_DRIVER} -url=${SECURITY_DB_URL} -user=${SECURITY_DB_USER} -password=${SECURITY_DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ../conf/migration:/flyway/sql
    depends_on:
      - db
#
#  app:
#    image: registry.gitlab.com/ideos.company/partech_platform/rebates-platform:${PLATFORM_IMAGE_TAG}
#    environment:
#      APPLICATION_SECRET: ${APPLICATION_SECRET}
#      JWT_SECRET: ${JWT_SECRET}
#      JWT_GRANT_EXPIRATION: ${JWT_GRANT_EXPIRATION}
#      JWT_ACCESS_EXPIRATION: ${JWT_EXPIRATION_TIMEOUT}
#      BCRYPT_SALT: ${BCRYPT_SALT}
#      SECURITY_DRIVER: ${SECURITY_DRIVER}
#      SECURITY_DB_URL: ${SECURITY_DB_URL}
#      SECURITY_DB_USERNAME: ${SECURITY_DB_USERNAME}
#      SECURITY_DB_USER: ${SECURITY_DB_USER}
#      SECURITY_DB_PASSWORD: ${SECURITY_DB_PASSWORD}
#      SECURITY_DB_CONNECTION_POOL: ${SECURITY_DB_CONNECTION_POOL}
#      SECURITY_DB_NUM_THREADS: ${SECURITY_DB_NUM_THREADS}
#      SECURITY_DB_TIMEOUT: ${SECURITY_DB_TIMEOUT}
#      SECURITY_DB_NAME: ${SECURITY_DB_NAME}
#      SECURITY_WEBAPP_HOST: ${SECURITY_WEBAPP_HOST}
#      SECURITY_MAILER_HOST: ${SECURITY_MAILER_HOST}
#      SECURITY_MAILER_PORT: ${SECURITY_MAILER_PORT}
#      SECURITY_MAILER_USER: ${SECURITY_MAILER_USER}
#      SECURITY_MAILER_PASSWORD: ${SECURITY_MAILER_PASSWORD}
#    ports:
#      - "9000:9000"
#    depends_on:
#      - flyway